Feature/configura lib
imobanco/fortes-webservice-wrapper pull request #1
Opened 2021-09-06 17:29 UTC by arianesc

2021-09-06 17:46 UTC, rodrigondec requested changes
Está bem encaminhado a LIB. 

Faltando só alguns ajustes agora!

O versioneer é um deles, posso fazer com você!

2021-09-06 17:46 UTC, rodrigondec commented on fortes_webservice_wrapper/wrapper/soap.py
> +        return Client(wsdl)
eu declararia um __init__ para configurar a url do WSDL. Justamente permitindo que fosse passado o argumento para o init ou então pegar do ENV1

2021-09-06 17:46 UTC, rodrigondec commented on fortes_webservice_wrapper/wrapper/fortes_ws.py
> +        return self.get_client(WSDL_URL)
Eu utilizaria só o método do BaseSoapWrapper direto!

2021-09-06 17:46 UTC, rodrigondec commented on pyproject.toml
> +name = "as-webservice-wrapper"
```suggestion
name = "fortes-wrapper"
```

2021-09-06 17:46 UTC, rodrigondec commented on workflows/pypi.yml
> +        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
Preciso adicionar permissão à esse secret nesse repósitório! Farei agora!

2021-09-06 17:46 UTC, rodrigondec commented on .github/workflows/tests.yml
> +
seria bom instalar todas as libs e utilizar um `make fmt.check`!

2021-09-06 17:48 UTC, arianesc commented on fortes_webservice_wrapper/wrapper/soap.py
> +        return Client(wsdl)
Eu não entendi bem se iria precisar dos outros métodos que tinham no seu `BaseSoapWrapper`,  por isso comecei esse só com o `get_client`.  Nesse caso vai precisar de USER e PASSWORD também?

2021-09-06 19:00 UTC, PedroRegisPOAR reviewed
Show! 

Muuuitos campos com nomes horríveis de manusear!

Tomando forma :rocket:

2021-09-06 19:00 UTC, PedroRegisPOAR commented on .github/workflows/pypi.yml
> +    runs-on: ubuntu-18.04
```suggestion
    runs-on: ubuntu-20.04
```

2021-09-06 19:00 UTC, PedroRegisPOAR commented on .github/workflows/tests.yml
> +    runs-on: ubuntu-18.04
```suggestion
    runs-on: ubuntu-20.04
```

2021-09-06 19:00 UTC, PedroRegisPOAR commented on .github/workflows/tests.yml
> +    runs-on: ubuntu-18.04
```suggestion
    runs-on: ubuntu-20.04
```

2021-09-06 19:00 UTC, PedroRegisPOAR commented on examples/soap/excluir_fornecedor.py
> +r = FortesWrapper().excluir_fornecedor_com_json(fornecedor)
Talvez mudar o nome para ficar no padrão dos outros?

```suggestion
r = FortesWrapper().excluir_fornecedor(fornecedor)
```

2021-09-06 19:00 UTC, PedroRegisPOAR commented on flake.nix
> +            #(pkgsAllowUnfree.poetry2nix.mkPoetryEnv config)
Por hora isso pode ser removido pois não funciona nem é usado.

```suggestion
        devShell = pkgsAllowUnfree.mkShell {
          buildInputs = with pkgsAllowUnfree; [
```

2021-09-06 19:00 UTC, PedroRegisPOAR commented on fortes_webservice_wrapper/models/base.py
> +class TClient(BaseModel):
Porque esse T, é a abreviação de que? Perdido rs

2021-09-06 19:00 UTC, PedroRegisPOAR commented on fortes_webservice_wrapper/wrapper/fortes_ws.py
> +        r = self.get_client().service.ExcluiClienteWithCNPJCPF(document)
Todos os outros estão com `Com`, apenas por padronização:
```suggestion
        r = self.get_client().service.ExcluiClienteComCNPJCPF(document)
```

2021-09-06 19:00 UTC, PedroRegisPOAR commented on poetry2nix.nix
> +}
Pode ser removido, não é usado.

2021-09-06 19:00 UTC, PedroRegisPOAR commented on mkPoetryEnv.nix
> +
Pode ser removido, não é usado.

2021-09-06 19:00 UTC, PedroRegisPOAR commented on setup.py
> +    version=0.1,
Talvez começar com `0.0.1` :thinking: 
```suggestion
from setuptools import setup

with open("README.md", "r") as fh:
    long_description = fh.read()

# Setting up
setup(
    name="fortes_webservice_wrapper",
    version=0.0.1,
```

2021-09-06 19:00 UTC, PedroRegisPOAR commented on tests/test_base.py
> +        self.assertEqual(result.json(), expected)
Nunca tinha visto assim! O `expected` é uma tupla de strings :astonished:

2021-09-06 19:06 UTC, arianesc commented on fortes_webservice_wrapper/wrapper/fortes_ws.py
> +        r = self.get_client().service.ExcluiClienteWithCNPJCPF(document)
Esses nomes que chamo depois do `.service` são os  métodos do `Fortes`, aí não posso alterar :crying_cat_face:

2021-09-06 19:07 UTC, PedroRegisPOAR commented on fortes_webservice_wrapper/wrapper/fortes_ws.py
> +        r = self.get_client().service.ExcluiClienteWithCNPJCPF(document)
> Esses nomes que chamo depois do `.service` são os métodos do `Fortes`, aí não posso alterar :crying_cat_face:

Entendi.

2021-09-06 19:07 UTC, arianesc commented on fortes_webservice_wrapper/models/base.py
> +class TClient(BaseModel):
Eu coloquei com `T` porque lá na documentação eles chamaram de `TCliente`, e se eu colocar só o `Client` podia confudir com um método do `Zeep` que também se chama `Client`.

2021-09-06 19:08 UTC, rodrigondec commented on fortes_webservice_wrapper/wrapper/soap.py
> +        return Client(wsdl)
Esses outros era como funcionava o soap da accesstage. O do fortes tem algum tipo de autenticação?

2021-09-06 19:13 UTC, arianesc commented on setup.py
> +    version=0.1,
Quando eu coloco `0.0.1` por algum motivo o `make fmt` quebra.

2021-09-09 14:03 UTC, rodrigondec approved these changes, later dismissed

2021-09-09 14:03 UTC, rodrigondec commented on fortes_webservice_wrapper/wrapper/soap.py
> +        self.wsdl = WSDL_URL
Com isso você deixa o usuário da LIB passar o argumento no init do wrapper também! Não obrigando ele a utilizar o ENV!

```suggestion
    def __init__(self, wsdl_url=None):
        if wsdl_url is None:
            self.wsdl = WSDL_URL
        else:
            self.wsdl = wsdl_url
        
```

2021-09-09 14:05 UTC, rodrigondec approved these changes, later dismissed

2021-09-09 14:07 UTC, rodrigondec approved these changes

2021-09-09 14:09 UTC, PedroRegisPOAR approved these changes
:rocket:

2021-09-09 14:10 UTC, merged